name: smartcaptart
services:
    ingress:
        build: .
        domainname: docker.local
        ports:
            - 8080:80
        restart: always
        depends_on:
          - backend
          - frontend

    frontend:
        build:
            context: frontend
        depends_on:
            - backend

    backend:
        build:
            context: backend
