name: smartcaptar
services:
    ingress:
        build: .
        domainname: docker.local
        ports:
            - 80:80
        restart: always
        depends_on:
          - backend
          - frontend

    frontend:
        build:
            context: frontend
        depends_on:
            - backend
        ports:
         - 8080:80
    backend:
        build:
            context: backend
